project  = "gitops-terraform-and-circleci"
region   = "europe-west2"
zone     = "europe-west2-a"
label = "main"
cidr_block    = "92.108.209.182/32"
backend_bucket = "tf-state-gitops-terraform-and-circleci"
credentials_file = "terraform-deploy.json"